@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeFontColor white

Package Model <<Rectangle>>{
show "{abstract}\nUser" fields
show RegisteredUser fields
show MovieInfo fields
show Theater fields
show Room fields
show ShowTime fields
show Seat fields
show Order fields
show PaymentInfo fields

show Room method


Class "{abstract}\nUser"
Class RegisteredUser
Class MovieInfo
Class Theater
Class Room
Class ShowTime
Class Seat
Class Order
Class PaymentInfo

class "{abstract}\nUser" {
    # email: String
    # password: String
    # userType: String
    # paymentInfo: PaymentInfo
}

class RegisteredUser {
}

class MovieInfo {
    - id: int
    - movieName: String
    - dateOfAnnounce: Date
    - duration: Time
}

class Theater {
    - id: int
    - name: String
    - address: String
}

class Room {
    - id: int
    - theaterID: int
    - roomNumber: int
    - nextAvailableTime: Date

    + void updateNextAvailableTime()
}

class Seat {
    - row: int
    - col: int
    - roomID: int
    - roomNum: int
    - isEarlyRegistration: boolean
    - isTaken: boolean
}

class ShowTime {
    - time: Timestamp
}

class PaymentInfo {
    - cardHolderName: String
    - cardNumber: String
    - cvv: int
}

class Order {
    - movie: MovieInfo
    - theater: Theater
    - showTime: ShowTime
    - showRoom: Room
    - seat: Seats
    - payment: PaymentInfo
}

legend
|= field |= method |=  |
|  <img:http://s.plantuml.com/private-field.png>     |   <img:http://s.plantuml.com/private-method.png>     | private |
|  <img:http://s.plantuml.com/protected-field.png>   |   <img:http://s.plantuml.com/protected-method.png>   | protected |
|  <img:http://s.plantuml.com/package-private-field.png>     |   <img:http://s.plantuml.com/package-private-method.png>    | package private |
|  <img:http://s.plantuml.com/public-field.png>     |   <img:http://s.plantuml.com/public-method.png>     | public |
end legend
@enduml
