@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor white

Package Model <<Rectangle>>{

Class User <<entity>>
Class RegisteredUser <<entity>>
Class MovieInfo <<entity>>
Class Theater <<entity>>
Class Room <<entity>>
Class ShowTime <<entity>>
Class Seat <<entity>>
Class Order <<entity>>
Class PaymentInfo <<entity>>
}

RegisteredUser .down.|> User

User "1" o-down- "0..*" PaymentInfo
User "1" o-down- "1" Order

PaymentInfo "1" -- "1..*" Order

Theater "1" o-right- "*" RegisteredUser
Theater "1" o-left- "*" MovieInfo
Theater "1" o-down- "*" Room

MovieInfo "1" - "1" Room

Room "1" o-- "0..*" ShowTime
Room "1" o-down- "20" Seat

Seat "1" -down- "1" Order
@enduml
