@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
box Frontend LOGIC_COLOR_T1
participant ":OrdinaryUser" as ou LOGIC_COLOR
participant ":RegistrationForm" as regForm LOGIC_COLOR
participant ":PaymentInfoForm" as paymentInfoForm LOGIC_COLOR
participant ":RegisteredUser" as ru LOGIC_COLOR
end box

box Database MODEL_COLOR_T1
participant ":Database" as database MODEL_COLOR
end box

[->ou

activate ou
ou -> regForm: input username and password
deactivate ou
activate regForm

regForm -> paymentInfoForm: input payment info
deactivate regForm
activate paymentInfoForm

paymentInfoForm -> ru: creates
deactivate paymentInfoForm
activate ru

ru -> database: register()
deactivate ru
activate database

@enduml